"""Generate academic literature review reports (Markdown and LaTeX)."""

from datetime import datetime
from typing import List, Dict
import os

class AcademicReporter:
    def generate_markdown(self, report_data: Dict) -> str:
        query = report_data.get("query", "Untitled")
        papers = report_data.get("papers", [])
        scores = report_data.get("scores", [])
        contradictions = report_data.get("contradictions", [])
        gaps = report_data.get("gaps", [])
        confidence = report_data.get("confidence", 0.0)
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        md = f"""# Literature Review: {query}

**Date:** {now}
**Number of Papers:** {len(papers)}
**Overall Confidence:** {confidence:.1f}%

## Executive Summary
{report_data.get("summary", "No summary available.")}

## Key Themes
{self._format_themes(report_data.get("themes", []))}

## Paper Analysis
"""
        for i, paper in enumerate(papers):
            s = scores[i] if i < len(scores) else {}
            authors = ", ".join(paper.get('authors', [])) if paper.get('authors') else "Anonymous"
            md += f"""
### Paper {i+1}: {paper.get('title', 'Untitled')}

- **Authors:** {authors}
- **Journal/Year:** {paper.get('journal', 'N/A')} ({paper.get('year', 'N/A')})
- **DOI:** {paper.get('doi', 'N/A')}
- **Source:** {paper.get('source', 'unknown')}
- **Scores:** Methodology {s.get('methodology', 0)}, Results {s.get('results', 0)}, Novelty {s.get('novelty', 0)}
- **Summary:** {paper.get('summary', 'No abstract')[:500]}...
"""

        if contradictions:
            md += "\n## Contradictions & Conflicting Findings\n"
            for c in contradictions:
                md += f"- **Finding A:** {c.get('finding_a')}\n"
                md += f"  **Finding B:** {c.get('finding_b')}\n"
                md += f"  **Conflict:** {c.get('conflict')}\n"
                md += f"  **Confidence:** {c.get('confidence')}\n"

        if gaps:
            md += "\n## Research Gaps\n"
            for g in gaps:
                md += f"- {g}\n"

        md += "\n## Methodology\n- Academic databases used: ArXiv, PubMed, OpenAlex\n- Confidence scoring: three-factor (methodology, results, novelty)\n- Contradiction detection via LLM synthesis\n- Rate limiting and SSRF protection applied\n"

        md += "\n## Full Citation List\n"
        for paper in papers:
            authors = ", ".join(paper.get('authors', [])) if paper.get('authors') else "Anonymous"
            title = paper.get('title', 'Untitled')
            md += f"- {authors} ({paper.get('year', 'n.d.')}). *{title}*. {paper.get('journal', '')}\n"

        md += "\n---\n*Report generated by Scrutator Academic.*"
        return md

    def generate_latex(self, report_data: Dict) -> str:
        md = self.generate_markdown(report_data)
        title = report_data.get("query", "Literature Review")
        
        # Simple escapes for LaTeX
        latex_content = md.replace("_", "\\_").replace("&", "\\&").replace("%", "\\%")
        
        latex = f"""\\documentclass{{article}}
\\usepackage{{hyperref}}
\\usepackage{{geometry}}
\\geometry{{margin=1in}}
\\title{{{title}}}
\\date{{{datetime.now().strftime("%B %d, %Y")}}}
\\begin{{document}}
\\maketitle

{latex_content}

\\end{{document}}"""
        return latex

    def _format_themes(self, themes: List[str]) -> str:
        if not themes:
            return "No themes identified."
        return "\n".join([f"- {t}" for t in themes])
